import type { Component } from 'solid-js';
import SidebarItem from './SidebarItem'

// based on a tailwind template I couldn't find again to credit
// if someone happens to find the original, please open a pr

const Sidebar: Component = () => {
	return (
		<div class="h-screen">
			<div class="bg-white rounded p-1 lg:p-3 h-screen shadow-lg overflow-y-scroll no-scrollbar">
				{/* TODO: Header */}
				{/* Item list */}
				<ul class="space-y-2 text-sm">
					{/* TODO: remove scrollbar on chromium */}
					<SidebarItem imageUrl="/src/dall-e.jpeg" /> {/* This image was generated by dall-e */}
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
					<SidebarItem imageUrl="/src/dall-e.jpeg" />
				</ul>
			</div>
		</div>
	);
};

export default Sidebar;
