import type { Component } from 'solid-js';

interface PropType {
	msg: string;
}

// based on https://tailwindcomponents.com/component/chat
const ChatMessage: Component<PropType> = (props) => {
	return (
		<div>
			{/* 1 div span per message box */}
			<div class="flex items-end">
				<div class="flex flex-col space-y-2 text-xs max-w-xs mx-2 order-2 items-start">
					<div><span class="px-4 py-2 rounded-lg inline-block bg-gray-300 text-gray-600">{props.msg}</span></div>
				</div>
				{/* Immage generated by dall-e mini */}
				<img src="/src/dallemini_2022-8-10_18-21-17.png" alt="My profile" class="w-6 h-6 rounded-full order-1" />
			</div>
		</div>
	);
};

export default ChatMessage;